// 生成唯一ID
export function generateId() {
  return `id_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
}

// 模拟数据
export const mockData = [
  {
    id: 'person_1',
    faceId: 'FACE_001',
    internalName: '主播A',
    externalName: '小智',
    sourceType: 'VIRTUAL_MAN_TYPE_SELF_PRESET',
    type: 'public',
    gender: 'male',
    age: 'youth',
    avatar: 'https://via.placeholder.com/50',
    authStartTime: '2024-01-01',
    authEndTime: '2024-12-31',
    customer: null,
    createdAt: '2024-01-01',
    images: [
      {
        id: 'image_1',
        imageKey: 'IMG_001',
        externalImageName: '小智-商务',
        thumbnail: 'https://via.placeholder.com/60',
        previewUrl: 'https://via.placeholder.com/200',
        format: 'horizontal',
        styles: ['商务', '正式'],
        industry: '本地生活',
        shelfStatus: 'shelved',
        authStartTime: '2024-01-01',
        authEndTime: '2024-12-31',
        expireTime: '2024-12-31',
        profession: '主持人',
        pose: '站立',
        proportion: '全身',
        season: '春季',
        scene: '室内',
        supportBackground: true,
        width: 1920,
        height: 1080
      },
      {
        id: 'image_2',
        imageKey: 'IMG_002',
        externalImageName: '小智-休闲',
        thumbnail: 'https://via.placeholder.com/60',
        previewUrl: 'https://via.placeholder.com/200',
        format: 'vertical',
        styles: ['休闲'],
        industry: '通用',
        shelfStatus: 'unshelved',
        authStartTime: '2024-01-01',
        authEndTime: '2024-12-31',
        expireTime: '2024-12-31',
        profession: '主持人',
        pose: '坐姿',
        proportion: '半身',
        season: '夏季',
        scene: '户外',
        supportBackground: false,
        width: 1080,
        height: 1920
      }
    ]
  },
  {
    id: 'person_2',
    faceId: 'FACE_002',
    internalName: '主播B',
    externalName: '小美',
    sourceType: 'VIRTUAL_MAN_TYPE_SELF_GENERATED',
    type: 'public',
    gender: 'female',
    age: 'youth',
    avatar: 'https://via.placeholder.com/50',
    authStartTime: '2024-02-01',
    authEndTime: '2024-11-30',
    customer: null,
    createdAt: '2024-02-01',
    images: [
      {
        id: 'image_3',
        imageKey: 'IMG_003',
        externalImageName: '小美-红衣',
        thumbnail: 'https://via.placeholder.com/60',
        previewUrl: 'https://via.placeholder.com/200',
        format: 'horizontal',
        styles: ['红衣', '商务'],
        industry: '食品饮料',
        shelfStatus: 'shelved',
        authStartTime: '2024-02-01',
        authEndTime: '2024-11-30',
        expireTime: '2024-11-30',
        profession: '导购',
        pose: '站立',
        proportion: '全身',
        season: '秋季',
        scene: '商场',
        supportBackground: true,
        width: 1920,
        height: 1080
      }
    ]
  },
  {
    id: 'person_3',
    faceId: 'FACE_003',
    internalName: '主播C',
    externalName: '老张',
    sourceType: 'VIRTUAL_MAN_TYPE_TENCENT_CLOUD',
    type: 'private',
    gender: 'male',
    age: 'middle',
    avatar: 'https://via.placeholder.com/50',
    authStartTime: '2024-03-01',
    authEndTime: '2024-10-31',
    customer: '客户A公司',
    createdAt: '2024-03-01',
    images: [
      {
        id: 'image_4',
        imageKey: 'IMG_004',
        externalImageName: '老张-正式',
        thumbnail: 'https://via.placeholder.com/60',
        previewUrl: 'https://via.placeholder.com/200',
        format: 'horizontal',
        styles: ['正式', '商务'],
        industry: '本地生活',
        shelfStatus: 'shelved',
        authStartTime: '2024-03-01',
        authEndTime: '2024-10-31',
        expireTime: '2024-10-31',
        userId: 'USER_001,USER_002',
        profession: '讲师',
        pose: '站立',
        proportion: '全身',
        season: '春季',
        scene: '会议室',
        supportBackground: true,
        width: 1920,
        height: 1080
      },
      {
        id: 'image_5',
        imageKey: 'IMG_005',
        externalImageName: '老张-休闲',
        thumbnail: 'https://via.placeholder.com/60',
        previewUrl: 'https://via.placeholder.com/200',
        format: 'vertical',
        styles: ['休闲'],
        industry: '通用',
        shelfStatus: 'unshelved',
        profession: '讲师',
        pose: '坐姿',
        proportion: '半身',
        season: '夏季',
        scene: '户外',
        supportBackground: false,
        width: 1080,
        height: 1920,
        unshelveReason: '授权过期',
        authStartTime: '2024-03-01',
        authEndTime: '2024-10-31',
        expireTime: '2024-10-31',
        userId: 'USER_001,USER_002'
      }
    ]
  }
]

